# Generated by Django 4.0.3 on 2022-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('text', models.TextField()),
                ('rank', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
